# Generated by Django 5.1.4 on 2024-12-13 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(default='Coordinador', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
                ('creditosSuperados', models.IntegerField()),
                ('creditosRestantes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('universidad_origen', models.CharField(choices=[('UCO', 'Universidad de Córdoba'), ('US', 'Universidad de Sevilla'), ('UMA', 'Universidad de Málaga'), ('UGR', 'Universidad de Granada')], default='UCO', max_length=100)),
                ('universidad_destino', models.CharField(choices=[('UCO', 'Universidad de Córdoba'), ('US', 'Universidad de Sevilla'), ('UMA', 'Universidad de Málaga'), ('UGR', 'Universidad de Granada')], default='UCO', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(default='2024-12-31')),
                ('motivo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('idUniversidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('programas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='sicue.universidad')),
            ],
        ),
    ]
