# Generated by Django 5.1.4 on 2024-12-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='sicue.alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
