# Generated by Django 5.1.4 on 2024-12-10 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('carrera', models.CharField(max_length=100)),
                ('promedio', models.FloatField()),
                ('creditosSuperados', models.IntegerField()),
                ('creditosRestantes', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('idUniversidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('programas', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Administrador',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='rol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='sicue.alumno')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sicue.profesor')),
                ('universidadDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_destino', to='sicue.universidad')),
                ('universidadOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_origen', to='sicue.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='sicue.universidad')),
            ],
        ),
    ]
