# Generated by Django 5.1.4 on 2024-12-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicue', '0002_alumno_profesor_universidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='rol',
            field=models.CharField(default='Coordinador', max_length=50),
        ),
    ]
